# Generated by Django 4.2.30 on 2026-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
